# Site settings
title: Cary's Blog
email: cary.hou.cn@gmail.com
description: > # 80后码农，热衷于折腾IT相关的事物。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caryhou.github.io" # the base hostname & protocol for your site
twitter_username: caryhou
github_username:  caryhou

# Build settings
markdown: kramdown
